### PR TITLE
Light dim fix

### PR DESCRIPTION
**Pull request by Bounz**
Made it possible to dim light with HomeGenieEchoBridge

### CODE REVIEW

**Comment by mralapete** [comment]
Could you also include the Control.AllLightsOn to turn all lights on in the network. I assume you will be using the Control.Level/# to control the dim level and not the Control.Dim which only dims 1 step as you know.

**Comment by Bounz** [comment]
@mralapete, how do you ask Alexa to turn on/off all lights?

**Comment by mralapete** [comment]
@Bounz the command I use is......
Alexa turn on Kitchen Light
Alexa turn off Kitchen Light

**Comment by Bounz** [comment]
And a _Kitchen Light_ is a single light or a group of lights?

**Pull request merged**
